### ISSUE TITLE
Latest BMC Helix ITSM Compatibility?

### ISSUE THREAD

**Issue by stevebestone** [gabeluci/ARInside#2]
Hi @gabeluci at our Company our BMC developers are regularely using ARInside. I am not a BMC Developer, but DevOps/Platform Engineer and I am wondering if ARInside can be used for the latest BMC Helix ITSM version.

As well as I am looking for solutions to provide ARInside in our Linuxed based cloud environment. On top of that, If I could somehow help/contribute to create a docker-version out of ARInside to enable running it as a container (localy as well as on a K8s Cluster), let me know.

PS: I am not a C++ Developer, but I could contribute on creating a GitHub Action Workflow to build with cmake and release it on Docker Hub if wanted :)

**Comment by gabeluci** [comment]
I just created a release today actually: https://github.com/gabeluci/ARInside/releases/tag/v3.1.4

The changes I made allows it to work when run against a Helix ITSM version. I'm not normally a C++ developer, so my changes were fairly limited. I updated it for our own use at my work since we're in the middle of upgrading. There are some caveats. Some of the newer objects related to Helix don't load and throw an error. This is because BMC isn't updating the C API anymore, so I could only use the latest 9.1 version, which doesn't understand any of the new stuff. I tried to minimize (hide) those errors. You may still see some when you run it, but it should still continue and complete the documentation without the objects that it failed on.

There is a Linux version as part of the release. I would be curious if it actually works as-is. I haven't actually tested it. I just compiled it and included the same (but updated) files that were included in the last release by the original developer.

The cloud stuff you mention sounds cool. If you feel like doing it, or need to do it for your own use anyway, by all means do so. I just don't know how much demand there would be for it. The 3.1.3 release was only downloaded 22 times since I released it three and a half years ago. But I know that the last version is still available from other sites, so this isn't a full picture of how much ARInside is used. I can leave this issue open and see if anyone else comes along and expresses some interest.

**Comment by jas0nmiller** [comment]
RE: full picture of how much ARInside is used.

I know there are numerous Remedy shops still using ARInside and are dreading they will no longer be able to use ARInside once they upgrade to a containerized version of Remedy (ok, fine, Helix). But the Remedy world is small so how many is that really? I know there is interest in keeping ARInside alive but it is so hard to put a number to it.

Almost 6 years ago a few of us Remedy friends decided we were going to build a new ARInside like tool from the ground up on Java. But once we gathered the requirements for an initial release (and even did a little coding) we came to the realization that the level effort and time needed to replace ARInside for a small, unknown number of organisations didn't make sense. Some of still kick the idea around occasionally but so far there hasn't been any movement.

**Comment by stevebestone** [comment]
@gabeluci Thanks for your answer. So to have a look about the possibilities, I would need some more information on how the building process is done. Currently I can only see the binary released, may you share the instructions on how to build the binary?

@jas0nmiller Sometimes I really wonder how BMC Software is still alive ;)

**Comment by gabeluci** [comment]
@jas0nmiller I agree: for those that use it, it's a lifesaver.

@wicked1133 I assume you're looking for compile instructions for Linux? To compile, clone the repository, and from the src directory:

```
mkdir build
cmake . -B ./build
cd build
make
```

There's nothing configured for `make install`, but I think this should do it (still from the build directory):

```
sudo cp ../thirdparty/arapi/lib/*.so /usr/lib
sudo ldconfig
sudo cp arinside /usr/bin
```

My Linux environment (actually Windows Subsystem for Linux) doesn't have access to my work Remedy environment, so I can't fully test it, but I can run `arinside` from the command line and see the help.

**Comment by stevebestone** [comment]
@gabeluci thanks for the instruction, that was what I needed. So far I am able to compile using docker image, but I get this errors:

```
/usr/local/include/c++/13.2.0/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
[ 97%] Building CXX object CMakeFiles/arinsidelib.dir/gzstream.cpp.o
[ 98%] Building CXX object CMakeFiles/arinsidelib.dir/stdafx.cpp.o
[ 99%] Linking CXX static library libarinsidelib.a
[ 99%] Built target arinsidelib
[ 99%] Building CXX object CMakeFiles/arinside.dir/ARInsideMain.cpp.o
[100%] Linking CXX executable arinside
/usr/bin/ld: /app/src/thirdparty/arapi/lib/libicudatabmc_lx64.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/arinside.dir/build.make:110: arinside] Error 1
make[1]: *** [CMakeFiles/Makefile2:168: CMakeFiles/arinside.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
> Note: It is not the full output, but I asume that's all you need, if you need the complete log, let me know.

May I ask what verison of CMake and which Arch (Linux OS System and Version) you are using to compile the source code? And do you have an idea where this issue comes from?

**Comment by gabeluci** [comment]
Interesting. That "file in wrong format" error seems to suggest that libicudatabmc_lx64.so was compiled for a different operating system than expected. But I didn't compile libicudatabmc_lx64.so - that came with the BMC C API.

I compiled in Ubuntu. I can't tell you the exact version right now since I'm not at home anymore. But I can get back to you later.

**Comment by stevebestone** [comment]
@gabeluci I took another look into the issue, and the problem is that I used a different platform arch to build the image than it was compiled with. Because my machine is arm and not amd based.

So, I fixed it using `docker build --platform linux/amd64 ...` instead of using my local ARCH, and I do not get the error when compiling anymore :)

Next step is to get arinside running inside the container...

**Comment by gabeluci** [comment]
Ah, ok. That makes sense 👍

**Comment by stevebestone** [comment]
Just a quick update on the ARInside Container Image - I've got it running and ARInside can run locally on Docker as well as be deployed to a k8s cluster using a CronJob to schedule the image to run and generate the `index.html`. 

here is the `Dockerfile` I created with the latest [Linux Release v3.1.4](https://github.com/gabeluci/ARInside/releases/tag/v3.1.4).

```dockerfile
# Use an official C++ development image as the base image
ARG GCC_VERSION=13.2.0
FROM --platform=linux/amd64 gcc:${GCC_VERSION}

# Set version
ARG ARINSIDE_VERSION=3.1.4
ARG ARINSIDE_ARCH=${ARINSIDE_VERSION}-linux_x64

# Set the working directory
WORKDIR /app

# Download and unzip file
RUN wget https://github.com/gabeluci/ARInside/releases/download/v${ARINSIDE_VERSION}/arinside-${ARINSIDE_ARCH}.zip \
  && unzip *${ARINSIDE_ARCH}.zip \
  && rm -f *${ARINSIDE_ARCH}.zip

# Install ARinside
RUN chmod +x arinside* \
  && cp arinside /usr/bin/ \
  && mv lib* /usr/lib/

# Copy Settings.ini from Host
COPY settings.ini .

# Run ARinside with settings
CMD ["arinside", "-i", "settings.ini"]
```

Build the Image
`docker build -t Arinside .`

Run the Image (requires `settings.ini` in your root folder where `Dockerfile` is located)
`docker run arinside`

Run the image with your own arguments if you need (will overwrite the default arguments from the Dockerfile.)
`docker run arinside arinside -s <hostname:port> -l <loginname> -p <password> -i settings.ini`

**Comment by markusmerker** [comment]
Hello,
I tried to run the latest ARInside Release on ITSM 21.3.10. While it genreated lots of files, it always throws an memory error after calling Line 910 "docMain->MessageList();" in ARInside.cpp. The same happens when I comment out the function. The error appears then after calling the Line 913 "docMain->NotificationList();". Nonetheless if I comment out this line too, ARInside loads completely. Only thing missing after that are Notifications and Messages.
I am not familiar with cpp and couldn't find a better solution myself.

**Comment by gabeluci** [comment]
@markusmerker Would you paste the entire output here please?

Edit: Is your computer just running out of RAM? It stores everything in memory before writing the files, so that can take up quite a bit of memory.

**Comment by markusmerker** [comment]
Sorry for the late response!
Here is a screenshot of the error which translates to "access violation when reading at position 0x000000000000"
![ARInsideerror](https://github.com/gabeluci/ARInside/assets/164906072/a01f0af9-8562-4cda-8066-f7c28526d934)
It happened between line 1417 and 1438 in DocMain.cpp

I dont think that my laptop runs out of ram. I tested it on two different PCs. One with 16GB and the other with 32GB.

**Comment by gabeluci** [comment]
Interesting.... Seems like a string is empty when it's not expected to be. That screenshot is helpful, but would you be able to go back in the stack trace to the ARInside code? When that error happens, double-click on "ARInside.exe!CDocMain::MessageList() Zeile 1415" in the Stack Trace (Aufrufliste) window.

Line 1415 is this:

```cpp
CARSchema schema(flt.GetSchemaList().u.schemaList[0].nameList[0]);
```

So maybe `nameList` is empty, which would probably be an easy fix, but sometimes the line numbers are wrong too. If you can set a breakpoint there, check the value of `flt.GetSchemaList().u.schemaList[0].numItems` and see if it's 0.

**Comment by gabeluci** [comment]
@markusmerker I committed a change to check the count in those arrays before using them. Can you update your code from the master branch and try again?

**Comment by markusmerker** [comment]
@gabeluci now it works fine. Thank you so much!

**Comment by gabeluci** [comment]
@markusmerker Awesome, thanks for confirming. I'll make a new release with these changes.

**Comment by gabeluci** [comment]
I created release [3.1.5](https://github.com/gabeluci/ARInside/releases/tag/v3.1.5).

@wicked1133 I also added your Dockerfile to the repository, referencing the new version. Thanks for that.
